name: A workflow for my Hello World file
on: push
env:
  GLOBAL_ENV_VAR : "GLOBAL ENV VAR"
  
jobs:

  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        env:
          TEST_IN_SHELL: "TEST IN SHELL"
        with:
          MY_NAME: "Rahul"
      - name: Test it!
        run: |
          echo "Test ${{ env.TEST_FROM_SHELL }}"
          echo "Test ${{ env.TEST_IN_SHELL }}"
          echo "Global Test ${{ env.GLOBAL_ENV_VAR }}"
          
  test:
    name: Check the variable is accesible here
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test it!
        run: |
          echo "Test ${{ env.TEST_FROM_SHELL }}"
          echo "Test ${{ env.TEST_IN_SHELL }}"
          echo "Global Test the input ${{ env.GLOBAL_ENV_VAR }}"
